# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b81f683d0aa1d0725894cc2d1e5d3b8fb0dc18a9b3a7694ef42ea74c6102e6d77c3e4651cf3b3661af37155c13fad08b0227fd456dfefdaca4fdaa3b97f0e122

test:
  secret_key_base: d7ec924347f7bd52089cfe8ae9a2f93373f34393c6d21909f5269d29b623e59c5ea9876a98d8b65c5ff72cf6e7beaf663e5a1073cf133a3863678d6e21a80464

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
